### ISSUE TITLE
Diffenator proofs

### ISSUE THREAD

**Issue by vv-monsalve** [djrrb/Bungee#108]
Hi @justvanrossum. The following are the diff images for the v2.000 pre-release fonts.

Please inspect them to revise the following:
- [x] Confirm the vertical metrics. The new values seem to be a good compromise for Vietnamese display fonts. However, if you want to make any changes, now would be the perfect time to do so.
- [x] `J` and `j` + `acutecomb` should work with dynamic composition for Dutch. This relates to our requirement for [soft dotted glyphs](https://googlefonts.github.io/gf-guide/diacritics.html#soft-dotted-glyphs).
- [x] Inspect the other `mark` and `mkmk` cases that look not fully working (e.g. `e̊` `ü̃́`)

### Bungee
![Bungee-reg](https://github.com/djrrb/Bungee/assets/48698976/ccc59c50-ed32-44dc-a834-f636b81f3472)

**Comment by justvanrossum** [comment]
I think I am fine with the new vertical metrics, but I don't have a strong opinion, so if you think they're fine, I'll go along with that.

Regarding the mark + mkmk features: I'm working on that in #109, will report back once I confirm the PR build works.

**Comment by justvanrossum** [comment]
Could you check the fonts from this run? https://github.com/djrrb/Bungee/actions/runs/7547329837

If you agree these indeed fix the issues you mention above, I will make a new release.

**Comment by vv-monsalve** [comment]
I'll run new checks and report back

**Comment by vv-monsalve** [comment]
The mark positions look mostly good now, with a few exceptions.
<img width="392" alt="Screen Shot 2024-04-23 at 17 46 36" src="https://github.com/djrrb/Bungee/assets/48698976/a6389c5f-e831-4a7b-a085-41e7393fe073">

However, some marks layering looks off

<img width="659" alt="Screen Shot 2024-04-23 at 17 45 48" src="https://github.com/djrrb/Bungee/assets/48698976/ac8d8aca-ec11-42b7-85a5-98b979409765">

**Comment by justvanrossum** [comment]
The E dot + acute _position_ may be fixable, but mark-to-base and mark-to-mark accents can't work in the Shade style.

I'm not sure what to do here. Perhaps we should remove the mark anchors for Shade so we don't get bad shapes.

**Comment by vv-monsalve** [comment]
> Perhaps we should remove the mark anchors for Shade so we don't get bad shapes.

Hi Just, We reviewed this today, and considering the unique features of the Bungee Shade font, we have decided to proceed with this option for the update and wait for user feedback. 
If we receive any complaints or requests for additional language support, we will review it from there.

**Comment by justvanrossum** [comment]
Hi Viviana, I have done this. Please check the latest run from this PR: https://github.com/djrrb/Bungee/actions/runs/8844751830

(I also added a fix a for an unrelated newer fontbakery check)

**Comment by vv-monsalve** [comment]
I've run new FB and Diffenator tests, and the fonts seem to be ready to go :)

There are only a few Warns that would be better for you to check before. They are reported in #110
