### ISSUE TITLE
Reported Warns 

### ISSUE THREAD

**Issue by vv-monsalve** [djrrb/Bungee#110]
These are the Warns reported for the fonts at https://github.com/djrrb/Bungee/actions/runs/8844751830

- This about the OFL update is required
<details>
    <summary>⚠️ <b>WARN</b> Check copyright namerecords match license file. <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/googlefonts.license.html#"></a></summary>
    <div>
> 
> A known licensing description must be provided in the NameID 14
> (LICENSE DESCRIPTION) entries of the name table.
> 
> The source of truth for this check (to determine which license is in use) is
> a file placed side-by-side to your font project including the licensing terms.
> 
> Depending on the chosen license, one of the following string snippets is
> expected to be found on the NameID 13 (LICENSE DESCRIPTION) entries of the
> name table:
> 
> - "This Font Software is licensed under the SIL Open Font License, Version 1.1.
> This license is available with a FAQ at: openfontlicense.org"
> 
> - "Licensed under the Apache License, Version 2.0"
> 
> - "Licensed under the Ubuntu Font Licence 1.0."
> 
> Currently accepted licenses are Apache or Open Font License. For a small set
> of legacy families the Ubuntu Font License may be acceptable as well.
> 
> When in doubt, please choose OFL for new font projects.
> 

> Original proposal: legacy:check/029

* ⚠️ **WARN** <p>Please consider updating the url from '<a href="https://scripts.sil.org/OFL">https://scripts.sil.org/OFL</a>' to '<a href="https://openfontlicense.org">https://openfontlicense.org</a>'.</p>
 [code: old-url]
</div>
</details>

**Comment by vv-monsalve** [comment]
- Adding a meta table is a strong suggestion. Which would help to avoid [issues like this one](https://github.com/fonttools/fontbakery/issues/4644)

<details>
    <summary>⚠️ <b>WARN</b> Ensure fonts have ScriptLangTags declared on the 'meta' table. <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/googlefonts.meta.html#"></a></summary>
    <div>


> 
> The OpenType 'meta' table originated at Apple. Microsoft added it to OT with
> just two DataMap records:
> 
> - dlng: comma-separated ScriptLangTags that indicate which scripts,
> or languages and scripts, with possible variants, the font is designed for.
> 
> - slng: comma-separated ScriptLangTags that indicate which scripts,
> or languages and scripts, with possible variants, the font supports.
> > 
> The slng structure is intended to describe which languages and scripts the
> font overall supports. For example, a Traditional Chinese font that also
> contains Latin characters, can indicate Hant,Latn, showing that it supports
> Hant, the Traditional Chinese variant of the Hani script, and it also
> supports the Latn script.
> 
> The dlng structure is far more interesting. A font may contain various glyphs,
> but only a particular subset of the glyphs may be truly "leading" in the design,
> while other glyphs may have been included for technical reasons. Such a
> Traditional Chinese font could only list Hant there, showing that it’s designed
> for Traditional Chinese, but the font would omit Latn, because the developers
> don’t think the font is really recommended for purely Latin-script use.
> 
> The tags used in the structures can comprise just script, or also language
> and script. For example, if a font has Bulgarian Cyrillic alternates in the
> locl feature for the cyrl BGR OT languagesystem, it could also indicate in
> dlng explicitly that it supports bul-Cyrl. (Note that the scripts and languages
> in meta use the ISO language and script codes, not the OpenType ones).
> 
> This check ensures that the font has the meta table containing the
> slng and dlng structures.
> 
> All families in the Google Fonts collection should contain the 'meta' table.
> Windows 10 already uses it when deciding on which fonts to fall back to.
> The Google Fonts API and also other environments could use the data for
> smarter filtering. Most importantly, those entries should be added
> to the Noto fonts.
> 
> In the font making process, some environments store this data in external
> files already. But the meta table provides a convenient way to store this
> inside the font file, so some tools may add the data, and unrelated tools
> may read this data. This makes the solution much more portable and universal.
> 

> Original proposal: https://github.com/fonttools/fontbakery/issues/3349

* ⚠️ **WARN** <p>This font file does not have a 'meta' table.</p>
 [code: lacks-meta-table]



</div>
</details>

**Comment by vv-monsalve** [comment]
- Please review and ensure the mark glyph class includes the reported marks.

<details>
    <summary>⚠️ <b>WARN</b> Check mark characters are in GDEF mark glyph class. <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/opentype.gdef.html#"></a></summary>
    <div>
> 
> Mark characters should be in the GDEF mark glyph class.
> 
> Original proposal: https://github.com/fonttools/fontbakery/issues/2877

* ⚠️ **WARN** <p>The following mark characters could be in the GDEF mark glyph class:
brevebelowcmb (U+032E), commaturnedabovecmb (U+0312), dieresisbelowcmb (U+0324), dotbelowcmb (U+0323), hookcmb (U+0309), horncmb (U+031B), macron (U+0304) and macronbelowcmb (U+0331)</p>
 [code: mark-chars]

</div>
</details>

**Comment by vv-monsalve** [comment]
- Please review if you would prefer to delete the SoftHypen. It's usually recommended to delete this character. See this [Fontbakery issue](https://github.com/fonttools/fontbakery/issues/4095)


<details>
    <summary>⚠️ <b>WARN</b> Does the font contain a soft hyphen? <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/universal.html#"></a></summary>
    <div>
> 
> The 'Soft Hyphen' character (codepoint 0x00AD) is used to mark
> a hyphenation possibility within a word in the absence of or
> overriding dictionary hyphenation.
> 
> It is sometimes designed empty with no width (such as a control character),
> sometimes the same as the traditional hyphen, sometimes double encoded with
> the hyphen.
> 
> That being said, it is recommended to not include it in the font at all,
> because discretionary hyphenation should be handled at the level of the
> shaping engine, not the font. Also, even if present, the software would
> not display that character.
> 
> More discussion at:
> https://typedrawers.com/discussion/2046/special-dash-things-softhyphen-horizontalbar
> 
> Original proposal: https://github.com/fonttools/fontbakery/issues/4046
> See also: https://github.com/fonttools/fontbakery/issues/3486

* ⚠️ **WARN** <p>This font has a 'Soft Hyphen' character.</p>
 [code: softhyphen]
</div>
</details>

**Comment by justvanrossum** [comment]
Thanks! Can you advice how to determine the appropriate language tags for the meta table?

**Comment by vv-monsalve** [comment]
We are currently adding the script information by default, `Latn` in this case. Now, if the font design includes any special `locl` for a specific language need, it should be specified in the `dlang`. 

```
  <meta>
    <text tag="dlng">
      Latn
    </text>
    <text tag="slng">
      Latn
    </text>
  </meta>
```

**Comment by vv-monsalve** [comment]
In the ufo files, this goes in the `lib.plist`
```
    <key>public.openTypeMeta</key>
    <dict>
      <key>dlng</key>
      <array>
        <string>Latn</string>
      </array>
      <key>slng</key>
      <array>
        <string>Latn</string>
      </array>
    </dict>
```

**Comment by justvanrossum** [comment]
Thanks! Added in https://github.com/djrrb/Bungee/pull/111/commits/8b2f2481d0a1e2e5c07f8683a29705ac8e8369b8

**Comment by justvanrossum** [comment]
I've merged the fixes. Let me know if there's anything else, or if you think it's time to tag a release.

**Comment by vv-monsalve** [comment]
Please ensure all of the above is applied to all the fonts (I've only seen Bungee Regular in the PR). Then I'll need to run a last QA round before PR to GF time :)

**Comment by vv-monsalve** [comment]
> or if you think it's time to tag a release.

Hi @justvanrossum, could you please confirm if you have applied the above changes to all the fonts? Now would be the time to tag the `v2.000` release and proceed with the update.

The longer we wait, the more FB is updated, and new Fails could be received from there ':-)

**Comment by justvanrossum** [comment]
All cupcakes here! I'll tag a release.

**Comment by vv-monsalve** [comment]
Excellent! 🥳

Should we add you as a designer, Just? (In the credits of the About section of the Specimen page in GF)

**Comment by justvanrossum** [comment]
> Should we add you as a designer, Just?

Thank you, but no, unless there is a possibility for an engineering credit. In that case Marte Verhaegen should also be mentioned.

**Comment by vv-monsalve** [comment]
Revisiting this Issue I noticed I didn't answer the above. No, there is no way to specify that credit, unless written as part of the Description of the font, in the About section of the Specimen page.
