### ISSUE TITLE
Bungee Layers Rotated fonts omitted from v2 release

### ISSUE THREAD

**Issue by djrrb** [djrrb/Bungee#119]
The v2 release contains “Bungee Layers” fonts, and “Bungee Rotated” fonts, but omits “Bungee Layers Rotated” fonts that were included in the original release ([see documentation here](https://github.com/djrrb/Bungee/blob/master/documentation/1-family-structure.md#bungee-layers-rotated)).

Since these are essentially legacy fonts at this point, I wouldn’t want to add a lot of work or complexity to the build process in order to produce them. But I did want to confirm that their omission was intentional...feel free to close if so!

**Comment by justvanrossum** [comment]
They are there, but are named differently:
<img width="275" alt="image" src="https://github.com/djrrb/Bungee/assets/4246121/050a9d82-6e13-40b9-bbc3-52f195c1e640">

The fact that they are named differently could easily be an oversight / mistake :(

**Comment by djrrb** [comment]
Ahh oops! :-D

So I guess what is missing is the Rotated version of the [“basic” styles](https://fonts.google.com/?query=bungee)?

**Comment by justvanrossum** [comment]
Hm, I don't think I've ever seen "Basic" rotated fonts. I can't find them in the latest 1.x release. Did they ever exist?

**Comment by djrrb** [comment]
Good lord I am losing my mind. Sorry about this! Closing this since the renaming is happening as part of #120

**Comment by justvanrossum** [comment]
No worries!
