### ISSUE TITLE
Script build for Google Fonts API (NAME table updates)

### ISSUE THREAD

**Issue by davelab6** [djrrb/Bungee#40]
The NAME table has a few things that I would like to request changing before the next build. 
- [ ] First is what I consider to be improvements that may be good to do for all possible contexts, by removing `Regular` from all 'family' and 'fullname' name records (both `nameID="1"` and `4`)

eg in `fonts/Bungee_TTF/Bungee-Regular.ttf` it is `Bungee Regular` and should be `Bungee`

(I noticed that in `Bungee-Regular.ttf` the family name being `Bungee Regular` meant the windows full name became `Bungee Regular Regular`, which is a bit odd - all should just be `Bungee` :) 
- [ ] Second, is adjusting the "Bungee Singles" fonts to make them fit snugly into the Google Fonts API. There are 5 files:
- `fonts/Bungee_TTF/Bungee-Regular.ttf`
- `fonts/Bungee_TTF/Bungee-Hairline.ttf`
- `fonts/Bungee_TTF/Bungee-Inline.ttf`
- `fonts/Bungee_TTF/Bungee-Outline.ttf`
- `fonts/Bungee_TTF/Bungee-Shade.ttf`

The Google Web Fonts API will present these as each a Regular (400 roman) instance for 5 different families, so the filenames should instead be,
- `fonts/Bungee_TTF/Bungee-Regular.ttf`
- `fonts/Bungee_TTF/BungeeHairline-Regular.ttf`
- `fonts/Bungee_TTF/BungeeInline-Regular.ttf`
- `fonts/Bungee_TTF/BungeeOutline-Regular.ttf`
- `fonts/Bungee_TTF/BungeeShade-Regular.ttf`
- [ ] Modulo the above point about `Bungee-Regular.ttf`, the `nameID="1"` values are all correct, but the PS name records (`nameID="6"`) should be the same as the filenames above, and Typographic Family Name records (`nameID="16"` and 17) should be removed.

**Comment by justvanrossum** [comment]
I'm assuming this has been resolved with the v2.000 release.
