### ISSUE TITLE
Vertical Kerning bug

### ISSUE THREAD

**Issue by davelab6** [djrrb/Bungee#42]
@behdad spotted a bug in the kerning; note in a TTX of `Bungee-Regular.ttf` how the coverage has one glyph in it, but ValueCount is zero:

```
        <SinglePos index="4" Format="2"> 
          <Coverage Format="1"> 
            <Glyph value="block.v"/> 
          </Coverage> 
          <ValueFormat value="0"/> 
          <!-- ValueCount=0 --> 
        </SinglePos> 
```

Removing the line `<Glyph value="block.v"/>` heals the font :)

**Comment by justvanrossum** [comment]
I can't find any evidence of this problem still persisting in the current release, so I'll close.
