### ISSUE TITLE
Link in project description goes to 404

### ISSUE THREAD

**Issue by impallari** [djrrb/Bungee#49]
The link at the top of the page (project description?) is wrong. 
![screen shot 2016-06-15 at 13 50 44](https://cloud.githubusercontent.com/assets/3036973/16089130/2eb5fe48-3300-11e6-903b-7016911cd919.png)
and goes to a 404 error page
![screen shot 2016-06-15 at 13 51 07](https://cloud.githubusercontent.com/assets/3036973/16089143/3e5e8c70-3300-11e6-9ce8-6db35d73c756.png)

**Comment by chrissam42** [comment]
Thanks, I've fixed the redirect, but @djrrb will have to fix the description.

**Comment by djrrb** [comment]
😳 Thank you Pablo! Fixed.
