### ISSUE TITLE
[question] Use PDF in SBIX font?

### ISSUE THREAD

**Issue by miguelsousa** [djrrb/Bungee#50]
Have you considered using PDFs instead of PNGs in the `sbix` font?

**Comment by djrrb** [comment]
You can do that!? It would be nice to make it less than 18MB... Thanks Miguel!

**Comment by miguelsousa** [comment]
Yep. The font will be smaller and the artwork will be scalable.
To get PDF files for all the glyphs I suggest taking the SVG files and converting them with [`svg2pdf`](http://wiki.inkscape.org/wiki/index.php/Tools#svg2pdf). Let me know if you need help with any of this. I'm already setup and it would take me less than an hour.

**Comment by RoelN** [comment]
I never knew about this either, very interesting! Small heads up, though: https://twitter.com/Lorp/status/744148497222479872

**Comment by miguelsousa** [comment]
Last time I checked it seemed to be working fine in Safari. I'll try to submit a PR soon, unless someone does it first.

**Comment by davelab6** [comment]
What goes into getting setup?

**Comment by colinmford** [comment]
Crazy question for @miguelsousa: have you ever tried to mix PNG and PDF strikes? Perhaps PNG for small sizes, PDF for large?

**Comment by miguelsousa** [comment]
@colinmford I have not.

**Comment by Crissov** [comment]
- [OTF 1.8 `sbix` table](http://www.microsoft.com/typography/otspec/sbix.htm)
- [Apple `sbix` documentation](http://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6sbix.html)

**Comment by applecuckoo** [comment]
Hmm, this issue seems to be no longer valid, with the release of version [1.2.0](https://github.com/djrrb/Bungee/releases/tag/v1.2.0) the SBIX font seems to have been dropped. Maybe close this issue?

**Comment by justvanrossum** [comment]
Yeah, this is not a route we should persue, IMO.
