### ISSUE TITLE
Remove XML and DOCTYPE headers from SVG artwork

### ISSUE THREAD

**Issue by miguelsousa** [djrrb/Bungee#51]
The SVG artwork contained in the OpenType-SVG font has these headers,
`<?xml version='1.0' encoding='UTF-8'?>`
`<!DOCTYPE svg  PUBLIC '-//W3C//DTD SVG 1.1//EN' 'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>`.
They can be removed.

**Comment by RoelN** [comment]
A post-processing script is used on the final fonts, which already removes the doctype. I'll add that it removes the XML tag. I submitted an issue with [RoboChrome](https://github.com/fontfont/RoboChrome/issues/10) which adds these headers, so they don't have to stripped out in the future.

**Comment by miguelsousa** [comment]
👍 BTW, there's at least one glyph that has the DOCTYPE.

**Comment by RoelN** [comment]
Ah, you're right — it's the one glyph I copied over manually to work around a small RoboChrome bug! Thanks for spotting that. I'll try to generate a new font later today, and put the postprocessing script in the repo here.
