### ISSUE TITLE
SBIX requires originOffset

### ISSUE THREAD

**Issue by djrrb** [djrrb/Bungee#54]
(Posting this on behalf of Dwayne from MS, who very helpfully sent a couple issues my way. @RoelN may be interested.)

Sbix glyphs need originOffset to be accurate. Currently the table says that the bottom left of the bitmap is the horizontal origin, but the horizontal origin is actually to the left of the PNG.

 This isn’t an issue for most sbix fonts because most sbix fonts are emoji, where the leftmost pixel of the PNG is usually the horizontal origin anyway, but it matters for text fonts because the sbix glyphs don’t align with other formats.

![unnamed-3](https://cloud.githubusercontent.com/assets/6578861/16233444/5be1e80a-379c-11e6-99fa-4039a65c4088.png)
![unnamed-2](https://cloud.githubusercontent.com/assets/6578861/16233447/604c4282-379c-11e6-974b-65f41cb3eb33.png)

**From DJR:** For some reason, BungeeColor alignments seem okay in textedit.

<img width="576" alt="screen shot 2016-06-21 at 10 39 34 am" src="https://cloud.githubusercontent.com/assets/6578861/16233474/7cb99064-379c-11e6-8ce3-c8c50543e9c9.png">

**Comment by djrrb** [comment]
More from Dwayne, related to issue #50:

> I know Windows 10 doesn’t support PDF in sbix, just PNG/JPEG/TIFF, but then Windows 10 also supports OT-SVG. So perhaps the sbix origin placement issue becomes a moot point if the sbix table is changed to use PDF graphic types, since Win 10 users would download the SVG or COLR version’s instead.

**Comment by applecuckoo** [comment]
@justvanrossum Also related to sbix font, can close now.
