### ISSUE TITLE
Bug: Bungee.js and the font do not load and work in Chrome and Safari

### ISSUE THREAD

**Issue by gusbemacbe** [djrrb/Bungee#59]
I copied the codes links of bungee.css and bungee.js and I changed `figure` to `h1`. It didn't work anything. The font and style weren't loaded.

It seems that Chrome and Safari accuses `bungee.js` of a problem with `function` because `$`.

```
bungee.js:283 Uncaught ReferenceError: $ is not defined
    at bungee.js:283
    at bungee.js:316
```

I download this zip and I tested the example file, it didn't work either in both Chrome and Safari:

![screen shot 2016-12-11 at 02 37 02](https://cloud.githubusercontent.com/assets/2257024/21078117/d916f672-bf4a-11e6-8752-1cb4c45f2c7c.png)

**Observation:** I would like to discard both horizontal and vertical. I removed horizontal and vertical from the class `h1`, but the text kept vertical.

**Comment by chrissam42** [comment]
Oops, bungee.js requires jQuery but this is not documented anywhere. I'll add that, and look into rewriting it to not require jQuery.

**Comment by gusbemacbe** [comment]
But I didn't forget of adding `jquery.min.js` link and it didn't work either. I noticed that the CSS file of Bungee, link distributed by Tester, in @djrrb's site, doesn't load the fonts because `https://` was omitted, therefore, Google Chrome and Safari accuse Bungee CSS of not loading the fonts.

**Comment by davelab6** [comment]
Hmm, when i tried https://github.com/djrrb/Bungee/tree/master/resources/web#example it worked fine for me in Chrome 57 on Mac OS X 10.10

<img width="1085" alt="screen shot 2016-12-11 at 15 02 01" src="https://cloud.githubusercontent.com/assets/261579/21082894/e2aa3e5c-bfb2-11e6-97be-e4010c110bdb.png">

**Comment by RoelN** [comment]
The links to the fonts are protocol-less, so if you open `example.html` as a local file in your browser (as is done in that first screenshot) this URL:

`//bungee-project.djr.com/fonts/Bungee_Web/BungeeLayers/BungeeLayers-Regular.woff`

will become

`file://bungee-project.djr.com/fonts/Bungee_Web/BungeeLayers/BungeeLayers-Regular.woff` which obviously fails. I don't get the jQuery error, though.
