### ISSUE TITLE
The font has different heights on Windows/Mac

### ISSUE THREAD

**Issue by CodeBrauer** [djrrb/Bungee#60]
Here is my codepen to test it: http://codepen.io/gab/pen/OWVrxa

The h1 has no margin and no padding. On Windows this h1 is 168px high, on mac 77px.

There seems to be an issue. I've already found some similar problems on SO.
- http://stackoverflow.com/questions/17597964/why-is-there-a-font-face-difference-in-line-height-on-windows-and-mac-os-x
- http://stackoverflow.com/questions/11726442/font-rendering-line-height-issue-on-mac-pc-outside-of-element

I just used the Google Font.

See screenshots:
![bs_win10_chrome_55 0](https://cloud.githubusercontent.com/assets/2059754/21746319/d2948bd2-d540-11e6-8ce9-d0c6c33290e8.jpg)
![bs_macsie_chrome_55 0](https://cloud.githubusercontent.com/assets/2059754/21746321/ddecd5ac-d540-11e6-9fbb-0d1f230b32aa.jpg)

**Comment by djrrb** [comment]
@CodeBrauer Thank you very much for reporting this!

@davelab6 I hesitate to change the vertical metrics without consulting you. Do you have updated guidelines on how these should be set in the fonts on Google Fonts?

Here are the current vertical metrics for Bungee Shade:

HHEA
```
    <ascent value="860"/>
    <descent value="-140"/>
    <lineGap value="200"/>
```

OS/2
```
    <sTypoAscender value="860"/>
    <sTypoDescender value="-140"/>
    <sTypoLineGap value="200"/>
    <usWinAscent value="1634"/>
    <usWinDescent value="914"/>
```

Let me know your recommendation, or your team are welcome to reset them.

**Comment by davelab6** [comment]
cc @m4rc1e

**Comment by davelab6** [comment]
Marc can explain :D

**Comment by m4rc1e** [comment]
Hey,

If the Use_Typo_Metrics flag is not enabled, which is the case here. Windows apps will use the usWinAscent, usWinDescent values.

Mac uses the hhea values.

The totals for both sets are the following:
hhea total = 1200
Win totals = 2548

These values should be self explanatory as to why the box is twice as large in the screenshot using Windows.

My recommendation is to not change these values, even though they are not ideal. by changing them, we may break users documents.

Thank you for flagging this up though.

**Comment by CodeBrauer** [comment]
@m4rc1e 
> My recommendation is to not change these values, even though they are not ideal. by changing them, we may break users documents.

But only if they update their fonts.
Using this font for the web is not possible than.

This can't be fixed by pure CSS since you can't specify CSS rules for windows/mac separately (without js/hacking around)

So, how about a new fixed "webfont-only"-version?

**Comment by m4rc1e** [comment]
Your example never set the css line-height property. By doing this, it overrides the vertical metrics. In a lot of css frameworks such as Bootstrap, they do this as a preflight. http://meyerweb.com/eric/tools/css/reset/ is rather common. This will give all fonts the same line length.

Check my fork out: http://codepen.io/anon/pen/EZvRJQ

OS X Safari:
![screen shot 2017-01-25 at 13 59 32](https://cloud.githubusercontent.com/assets/7525512/22293278/f7f332ce-e306-11e6-9704-40905267ccd4.png)

Win 7 Chrome:
![screen shot 2017-01-25 at 13 59 16](https://cloud.githubusercontent.com/assets/7525512/22293330/1128ffbc-e307-11e6-863b-f466b78b4a4f.png)

This is an issue for text editors which use the font's vertical metrics and don't offer user control.

Cheers,
Marc

**Comment by CodeBrauer** [comment]
Thanks @m4rc1e ! Not the best way, but at least this is a good way!

**Comment by djrrb** [comment]
Thanks @m4rc1e!
