### ISSUE TITLE
User cannot access Bungee-Shade banner glyphs in Photoshop 

### ISSUE THREAD

**Issue by djrrb** [djrrb/Bungee#61]
Using v1.1.0, a user contacted me saying he cannot access banner glyphs using Bungee-Shade. Regardless of which u+2022-encoded glyph he selects from the glyph palette, the arrow shows up. Running Photoshop 2017 on Windows. I cannot duplicate this with Photoshop 2017 on Mac.

![unnamed](https://cloud.githubusercontent.com/assets/6578861/22633221/8bf2b8fc-ebed-11e6-8f4e-da835791e30a.png)

Next steps are to test on Windows and diagnose.

**Comment by justvanrossum** [comment]
Would be nice if someone could check the situation with the lastes Bungee release and a contemporay version of Photoshop.

**Comment by djrrb** [comment]
This seems fine 
<img width="1470" alt="Screenshot 2024-07-05 at 5 46 53 PM" src="https://github.com/djrrb/Bungee/assets/6578861/576ba1f4-2e72-4986-819b-d7241e3c1dc7">
