### ISSUE TITLE
[Question] - Bungee Shade - Opposite Shadow Direction

### ISSUE THREAD

**Issue by matthewhartman** [djrrb/Bungee#72]
Hey @djrrb !

First off, thank you so much for this amazing font! I am absolutely loving it!

I was wondering if you offered a variant of the Bungee Shade with the shadow going in the opposite direction?

I have attached a really crude example below (your font is a lot more elegant is it connects and gives a more 3D look)
![bungee-invert](https://user-images.githubusercontent.com/1294141/140674304-d1f86875-baf6-40bb-b028-ad5877358ef1.png)
.

Let us know what you think and thanks again mate! :+1:

**Comment by matthewhartman** [comment]
Late reply, but I think I can get around this using some CSS magic. I ended up using the Bungee font and added some text shadows to get this effect. Thanks anyway :)

**Comment by djrrb** [comment]
Hi Matthew,

Thanks for following up, and sorry for the delayed response. I was looking into how easy it would be to automate this for you, and while I made some progress, I think you’re probably better off with the CSS solution you found!

Thanks so much for using Bungee, and sending you my warmest regards!

<img width="713" alt="Screen Shot 2021-11-11 at 4 27 28 PM" src="https://user-images.githubusercontent.com/6578861/141371460-6d354ec5-99ec-4c25-9972-f80466379bb2.png">

**Comment by matthewhartman** [comment]
Thanks @djrrb ! :love_you_gesture:
