### ISSUE TITLE
Would it be an idea to delete all lowercase, and double-encode the uppercase instead?

### ISSUE THREAD

**Issue by justvanrossum** [djrrb/Bungee#81]
I wonder if there would be any downsides. (Assuming all lc are identical to their uc counterparts.)

**Comment by djrrb** [comment]
I’m generally a fan of double-encoding and do it when I can. In Bungee, all LC should be identical to their UC counterparts.

I can’t remember if I was asked to make the extra lowercase glyphs for Bungee, but I have been asked to do this in the past by font engineers where were concerned about some possible [edge-cases](https://typedrawers.com/discussion/comment/22367/#Comment_22367)...something about picking up the wrong encoding when copying/pasting out of a PDF file?

However it looks like there is an open issue about this in fontbakery from a couple months ago and Marc says it should pass with double-encodings...so I think you’re good to proceed! https://github.com/googlefonts/fontbakery/issues/3817

If someone thought a single-encoded font is more robust, it would also be possible to create the LC glyphs during the build process, which would simplify the sources quite a bit.

**Comment by djrrb** [comment]
Just adding a note that it’ll still need a solution for the lowercase that don’t map directly to an uppercase: dotlessi, dotlessj, germandbls, etc.

**Comment by justvanrossum** [comment]
It may not be worth the effort, and I'm afraid to break things... Maybe it's too risky, and easier to leave things be.
