### ISSUE TITLE
Bungee Spice colors reversed from Google Fonts release

### ISSUE THREAD

**Issue by djrrb** [djrrb/Bungee#90]
Our version from Release 1.2.1 has colors that are reversed from the original release on Google Fonts.

<img width="1829" alt="Screenshot 2023-08-02 at 4 58 13 PM" src="https://github.com/djrrb/Bungee/assets/6578861/5e335c56-89c8-4dee-aab5-5a7c8bfec5c2">

Would be cool to include multiple palettes with both! (and more?)

**Comment by justvanrossum** [comment]
Oops! Will send a fix.

Yes, multiple palettes could be nice.

**Comment by justvanrossum** [comment]
Turns out, the build PR does produce the correct gradient, but I just stupidly sent you a stale copy.

Here's a correct one:
[BungeeSpice-Regular-COLRv1.ttf.zip](https://github.com/djrrb/Bungee/files/12247969/BungeeSpice-Regular-COLRv1.ttf.zip)
