### ISSUE TITLE
Vertical Metrics consistency

### ISSUE THREAD

**Issue by vv-monsalve** [djrrb/Bungee#93]
The fonts currently published to Google Fonts don't follow the [vertical metrics specifications](https://googlefonts.github.io/gf-guide/metrics.html), resulting in inconsistency across platforms, and appearing too wide on Windows. 

In preparation for the new fonts update, they should follow the spec. However, due to the significant difference, we can't apply the strategy of inheriting the Win metrics, in which case, an overall regression must be accepted and a new compromise between platforms should be made.

Please find the current and proposed values below, with comparative images between them.

#### Current values

| Metrics         | Bungee | Hairline | Inline | Outline | Shade | Spice |
|----------------|--------|----------|--------|---------|-------|-------|
|sTypoAscender   |   860  |   860    |   860  |   860   |   860 |   860 |
|sTypoDescender  |  -140  |  -140    |  -140  |  -140   |  -140 |  -140 |
|sTypoLinegap    |   200  |   200    |   200  |   200   |   200 |   200 ||
|hhea Ascender   |   860  |   860    |   860  |   860   |   860 |   860 |
|hhea Descender  |  -140  |  -140    |  -140  |  -140   |  -140 |  -140 |
|hhea Linegap    |   200  |   200    |   200  |   200   |   200 |   200 |
|winAscent       |  1634  |  1614    |  1634  |  1644   |  1634 |  1138 |
|winDescent      |   914  |   894    |   914  |   924   |   914 |   362 |

#### Requirements and new values proposed

- Changing the Typo and hhea values, and keeping the win metrics for each family (to avoid clipping)
- Linegaps == 0
- Use of Typo Metrics _must_ be enabled

| Metrics         | Bungee | Hairline | Inline | Outline | Shade | Spice |
| ----------------|--------|----------|--------|---------|-------|-------|
| sTypoAscender   |  1020  |  1020    |  1020  |  1020   |  1020 |  1020 |
| sTypoDescender  |  -300  |  -300    |  -300  |  -300   |  -300 |  -300 |
| sTypoLinegap    |     0  |     0    |     0  |     0   |     0 |     0 |
| hhea Ascender   |  1020  |  1020    |  1020  |  1020   |  1020 |  1020 |
| hhea Descender  |  -300  |  -300    |  -300  |  -300   |  -300 |  -300 |
| hhea Linegap    |     0  |     0    |     0  |     0   |     0 |     0 |
| winAscent       |  1634  |  1614    |  1634  |  1644   |  1634 |  1138 |
| winDescent      |   914  |   894    |   914  |   924   |   914 |   362 |

#### Comparative images
Old = GF distributed / New = proposed values

**Windows**
![Win-before-after](https://github.com/djrrb/Bungee/assets/48698976/498c4ef8-1d07-4f99-b2a8-6d9df3a9d4d1)

**Mac**
![Mac-before-after](https://github.com/djrrb/Bungee/assets/48698976/d98e1760-8bd4-4e56-aff4-b36e1fa4c870)

**Comment by justvanrossum** [comment]
We'll imlement this very soon, thanks for the suggested new values!

**Comment by vv-monsalve** [comment]
Excellent news! The values were calculated as an average between the current values for both Windows and Mac, and also to give a prudent space for stacked diacritics. Considering that this is an all-caps display font, the leading has been kept a bit tight while also making a compromise for the Vietnamese accents. 

You can test the suggestions and make further tweaks if needed, as long as they fall within our [recommended range of 120% to 130% for the leading](https://googlefonts.github.io/gf-guide/metrics.html#11-the-sum-of-the-fonts-vertical-metric-values-absolute-should-be-20-30-greater-than-the-fonts-upm) :)

**Comment by justvanrossum** [comment]
I'd be happy to stick to your recommendations.

The only thing I'm worried about is what fontbakery will say: there are a couple of "oversized" glyphs tha go way over or under. I think the following are the most extreme: `uni21AB.arrow` and `uni21AC.arrow`:

<img width="1145" alt="image" src="https://github.com/djrrb/Bungee/assets/4246121/9d4f1e5e-a4e1-4782-b9f8-2574e130d789">

**Comment by justvanrossum** [comment]
The winAscent and winDescent values for the COLR fonts may be different than the suggestions, as they have a larger glyph set now than the released versions had.

**Comment by vv-monsalve** [comment]
> The only thing I'm worried about is what fontbakery will say: there are a couple of "oversized" glyphs that go way over or under. I think the following are the most extreme: uni21AB.arrow and uni21AC.arrow:

Yes, I saw those oversized glyphs but prioritized the text and did not consider them in the VM calculations. Otherwise, the leading would end up being too loose for the text.

> The winAscent and winDescent values for the COLR fonts may be different than the suggestions, as they have a larger glyph set now than the released versions had.

Sure!
