### ISSUE TITLE
Missing lines for peso, peseta and naira in outline style?

### ISSUE THREAD

**Issue by martelahaie** [djrrb/Bungee#95]
While checking the fonts build with the new script, @justvanrossum and I saw that in the original outline fonts the peso, peseta and naira have missing inlines (see third column). We are curious if we should keep these exceptions as they were (without inlines) or if we should add the inlines in the new fonts.

<img width="618" alt="Screenshot 2023-09-28 at 10 59 46" src="https://github.com/djrrb/Bungee/assets/103949453/88b5c620-ca17-453e-b206-d3538fbe62ae">

**Comment by djrrb** [comment]
I think this is an error, and it makes sense to add the horizontal stroke inlines so that these are the same across the board. Thank you!

**Comment by justvanrossum** [comment]
Since the new build already adds these strokes, I think this issue can be closed without any futher action. Right, @martelahaie?

**Comment by martelahaie** [comment]
Yes that sounds right
