### ISSUE TITLE
Inconsistencies with /Lslash.v slash contour

### ISSUE THREAD

**Issue by martelahaie** [djrrb/Bungee#97]
Hello @djrrb ! Another contour question: the position of the slash in Lslash.v seems to be different across all the 2-build/Bungee_Basic files, most notably in the 'inline' and 'shade' styles (see old build fonts column).
Currently in the new build script, the slash gets the same position everywhere (see new build fonts column).

Would it be okay to keep the new build like that or would you prefer the old positions of the slash?
<img width="574" alt="Screenshot 2023-10-11 at 07 52 11" src="https://github.com/djrrb/Bungee/assets/103949453/c38345f4-2ea4-45fa-914d-4e7a05fb949f">

**Comment by djrrb** [comment]
Hi @martelahaie thanks for catching this!

I don’t have strong feelings on this, except to say that I think it’s worth fudging the shade so that the interior space is completely filled in, like in `Lslash` and we don’t get that skinny white shape. How do you feel about that?

**Comment by martelahaie** [comment]
Yes I also think that it's worth avoiding the skinny white shape here.
Then this will be another exception for the build script @justvanrossum.

**Comment by justvanrossum** [comment]
Hm this exception may be of a different kind than the other ones for Basic Shade, as it would be relevant for layering, too.

Do you see a way to tweak all 1-build layers `Lslash.v` so we don't have to make an exception? Even if that means that `Lslash.v` will be ever so slightly different in all versions compared to the released fonts.

**Comment by martelahaie** [comment]
<img width="107" alt="Screenshot 2023-10-12 at 11 24 15" src="https://github.com/djrrb/Bungee/assets/103949453/137e2ace-2812-48c8-88f4-a692448f69f8">

The old layer fonts don't follow the Lslash exception, but they probably should be the same.


<img width="331" alt="Screenshot 2023-10-12 at 11 20 16" src="https://github.com/djrrb/Bungee/assets/103949453/aa9a673b-7805-4e40-853f-a86ed13e4310">

The two easiest adjustments would be to either move the slash (like the earlier exceptions) or elongate it. 
I feel like elongating would be the least noticeable tweak, while still staying close to the non-vertical Lslash.
